# -*- coding: utf-8 -*-
"""01_expressions.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13kHvCMIV7o9MnBzOS_oTEg0U6xWDRkOl

# **01_dicesimulator.**

Problem Statement
Simulate rolling two dice, three times. Prints the results of each die roll. This program is used to show how variable scope works.
"""

import random
print ("01_dicesimulator")

def roll_dice():
  die1:int = random.randint(1,6)
  die2:int = random.randint(1,6)
  total:int = die1 + die2
  print(f"Total of two dies:{total}")

def main():
   die1: int = 10
   print("diel in main() start as :" + str(die1))
   roll_dice()
   roll_dice()
   roll_dice()
   print("diel in main()is :" + str(die1))

if __name__ == "__main__":
   main()

"""# **02_e=mc2**

Problem Statement
Write a program that continually reads in mass from the user and then outputs the equivalent energy using Einstein's mass-energy equivalence formula (E stands for energy, m stands for mass, and C is the speed of light:

E = m * c**2

Almost 100 years ago, Albert Einstein famously discovered that mass and energy are interchangeable and are related by the above equation. You should ask the user for mass (m) in kilograms and use a constant value for the speed of light -- C = 299792458 m/s.

Here's a sample run of the program (user input is in bold italics):

Enter kilos of mass: 100

e = m * C^2...

m = 100.0 kg

C = 299792458 m/s

8.987551787368176e+18 joules of energy!
"""

print("02_e=mc2")

def energy():
  c = 299792458
  m = float(input("Enter kilos of mass: "))
  print("e = m * C^2")
  print("Mass :" + str(m) + "kg")
  print("C :" + str(c) + "m/s")
  print("e =" + str(m * c**2) + "joules of energy!")

if __name__ == "__main__":
   energy()

"""# **03_feet_to_inches.**

Problem Statement
Converts feet to inches. Feet is an American unit of measurement. There are 12 inches per foot. Foot is the singular, and feet is the plural.
"""

print("03_feet_to_inches.")

inch:int = 12

def foot():
  feet:int = int(input("Enter feet I will convert it into inches: "))
  print(f"There are {feet * inch} inches in {feet} feet")

if __name__ == "__main__":
   foot()

"""# **04_pythagorean_theorem**

Problem Statement
Write a program that asks the user for the lengths of the two perpendicular sides of a right triangle and outputs the length of the third side (the hypotenuse) using the Pythagorean theorem!

The Pythagorean theorem, named after the ancient Greek thinker, Pythagoras, is a fundamental relation in geometry. It states that in a right triangle, the square of the hypotenuse is equal to the sum of the square of the other two sides.

For instance, let's consider a right triangle ABC, with the right angle located at C. According to the Pythagorean theorem:

BC ** 2 = AB ** 2 + AC ** 2

Your code should read in the lengths of the sides AB and AC, and that outputs the length of the hypotenuse (BC). You will probably find math.sqrt() to be useful.

Here's a sample run of the program (user input is in bold italics):

Enter the length of AB: 3

Enter the length of AC: 4

The length of BC (the hypotenuse) is: 5.0
"""

print("04_pythagorean_theorem")
import math

def tringle():
 ab:float = float(input("Enter the length of AB: "))
 ac:float = float(input("Enter the length of AC: "))
 bc:float = math.sqrt(ab**2 + ac**2)
 print(f"The length of BC (the hypotenuse) is: " + str(bc))

if __name__ == "__main__":
   tringle()

"""# **05_remainder_division**

Problem Statement
Ask the user for two numbers, one at a time, and then print the result of dividing the first number by the second and also the remainder of the division.

Here's a sample run of the program (user input is in bold italics):

Please enter an integer to be divided: 5

Please enter an integer to divide by: 3

The result of this division is 1 with a remainder of 2
"""

print("05_remainder_division")

def remainder():
  num1:int = int(input("Please enter an integer to be divided: "))
  num2:int = int(input("Please enter an integer to divide by: "))
  quotient :int = num1 // num2
  remainder:int = num1 % num2
  print(f"The result of this division is {quotient } with a {remainder}")

if __name__ == "__main__":
   remainder()

"""# **06_rolldice.**
Problem Statement
Simulate rolling two dice, and prints results of each roll as well as the total.
"""

print("06_rolldice.")
import random

def rolldice():
  dice1:int = random.randint(1,6)
  dice2:int = random.randint(1,6)
  total:int = dice1 + dice2
  print(f"Dice 1: {dice1}")
  print(f"Dice 2: {dice2}")
  print(f"Total of two dies:{total}")
if __name__ == "__main__":
   rolldice()

"""# **06_seconds_in_year**

Problem Statement
Use Python to calculate the number of seconds in a year, and tell the user what the result is in a nice print statement that looks like this (of course the value 5 should be the calculated number instead):

There are 5 seconds in a year!

You should use constants for this exercise -- there are 365 days in a year, 24 hours in a day, 60 minutes in an hour, and 60 seconds per minute.
"""

print("06_seconds_in_year")

def number_of_seconds():
  days_in_year:int = 365
  hours_in_day:int = 24
  minutes_in_hour:int = 60
  seconds_in_minute:int = 60
  total_seconds:int = days_in_year * hours_in_day * minutes_in_hour * seconds_in_minute
  print(f"There are {total_seconds} seconds in a year!")

if __name__ == "__main__":
   number_of_seconds()

"""# **07_tiny_mad_lib**

Problem Statement
Write a program which prompts the user for an adjective, then a noun, then a verb, and then prints a fun sentence with those words!

Mad Libs is a word game where players are prompted for one word at a time, and the words are eventually filled into the blanks of a word template to make an entertaining story! We've provided you with the beginning of a sentence (the SENTENCE_START constant) which will end in a user-inputted adjective, noun, and then verb.

Here's a sample run (user input is in bold italics):

Please type an adjective and press enter. tiny

Please type a noun and press enter. plant

Please type a verb and press enter. fly

Code in Place is fun. I learned to program and used Python to make my tiny plant fly!
"""

print("07_tiny_mad_lib")

def mad_lib():
  noun:str = str(input("Please type a noun and press enter. "))
  adjective:str = str(input("Please type an adjective and press enter. "))
  verb:str = str(input("Please type a verb and press enter. "))
  print(f"Do you {verb} your {adjective} {noun} !")

if __name__ == "__main__":
   mad_lib()