# -*- coding: utf-8 -*-
"""02_lists.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10dQkM0xY0kJ0bPqXoUAA9rNZnN0G4Kf6

# **01_add_many_number**

Problem Statement
Write a function that takes a list of numbers and returns the sum of those numbers.
"""

print("01_add_many_number")

def add_num(numbers) ->int:
  num:int = 0
  for i in numbers:
    num += i
  return num

def main():
  numbers:list[int] = [1, 2, 3, 4,5]
  sum = add_num(numbers)
  print(sum)

if __name__ == "__main__":
    main()

"""# **02_double_list**

Problem Statement
Write a program that doubles each element in a list of numbers. For example, if you start with this list:

numbers = [1, 2, 3, 4]

You should end with this list:

numbers = [2, 4, 6, 8]
"""

from ast import Index
from re import I
print("02_double_list")

def main():
  numbers:list[int] = [1,2,3,4,5]
  for i in range(len(numbers)):
    Index = numbers[i]
    numbers[i] *= 2
  print(numbers)

if __name__ == "__main__":
    main()

"""## **03_erase_canva**
Problem Statement
Implement an 'eraser' on a canvas.

The canvas consists of a grid of blue 'cells' which are drawn as rectangles on the screen. We then create an eraser rectangle which, when dragged around the canvas, sets all of the rectangles it is in contact with to white.
"""

print("03_erase_canva")`

def erase_canvas(canvas, eraser):
  for cell in canvas:
    if cell.colliderect(eraser):
      cell.fill((255, 255, 255))
      canvas.remove(cell)

      return canvas

def main():
  canvas = [pygame.Rect(x*50, y*50, 50, 50) for x in range(10) for y in range(10)]
  eraser = pygame.Rect(0, 0, 50, 50)
  erase_canvas(canvas, eraser)
  print(canvas)

if __name__ == "__main__":
    main()

"""# **04_flowing_with_data_structures**

Problem Statement
In the information flow lesson, we discussed using a variable storing a number as an example of scope. We saw that changes we made to the number inside a function did not stay unless we returned it. This is true for what we call immutable data types which include things like numbers and strings.

However, there are also mutable data types where changes stay even if we don't return anything. Some examples of mutable data types are lists and dictionaries. This means that you should be mindful when modifying lists and dictionaries within helper functions since their changes stay whether or not you return them.

To see this in action, fill out the add_three_copies(...) function which takes a list and some data and then adds three copies of the data to the list. Don't return anything and see what happens! Compare this process to the x = change(x) example and note the differences.

Here is an example run of this program (user input in bold italics):

Enter a message to copy: Hello world!

List before: []

List after: ['Hello world!', 'Hello world!', 'Hello world!']

(Note. The concept of immutable/mutable data types is called mutability. Be careful because different programming languages have different rules regarding mutability!)
"""

print("04_flowing_with_data_structures")

def add_three_copies(lst, data):
  for i in range(3):
    lst.append(data)

def main():
  message = input("Enter a message to copy: ")
  lst = []
  print("List before:", lst)
  add_three_copies(lst, message)
  print("List after:", lst)

if __name__ == "__main__":
    main()

"""# **05_get_first_element**

Problem Statement
Fill out the function get_first_element(lst) which takes in a list lst as a parameter and prints the first element in the list. The list is guaranteed to be non-empty. We've written some code for you which prompts the user to input the list one element at a time.
"""

print("05_get_first_element")

def get_first_element(lst):
  print(lst[0])

def get_list():
  lst = []
  elem:int = input("Enter an element add to the list: ")
  while elem != "":
    lst.append(elem)
    elem = input("Enter an element add to the list: ")
  return lst

def main():
    lst = get_list()
    get_first_element(lst)

if __name__ == "__main__":
    main()

"""# **06_get_last_element**

Problem Statement
Fill out the function get_last_element(lst) which takes in a list lst as a parameter and prints the last element in the list. The list is guaranteed to be non-empty, but there are no guarantees on its length.
"""

print("06_get_last_element")

def get_last_element(lst):
  print(lst[-1])

def get_list():
  lst = []

  elem:int = input("Enter an element add to the list: ")
  while elem != "":
    lst.append(elem)
    elem = input("Enter an element add to the list: ")
  return lst

def main():
    lst = get_list()
    get_last_element(lst)

if __name__ == "__main__":
    main()

"""# **07_get_list**

Problem Statement
Write a program which continuously asks the user to enter values which are added one by one into a list. When the user presses enter without typing anything, print the list.

Here's a sample run (user input is in blue):

Enter a value: 1 Enter a value: 2 Enter a value: 3 Enter a value: Here's the list: ['1', '2', '3']
"""

print("07_get_list")

def get_list():
  lst = []
  val:int = input("Enter a value to add to the list. ")
  while val!= "":
    lst.append(val)
    val = input("Enter a value to add to the list. ")
  return lst

def main():
  lst = get_list()
  print("Here's the list:", lst)

if __name__ == "__main__":
      main()

"""# **08_shorten**
Problem Statement
Fill out the function shorten(lst) which removes elements from the end of lst, which is a list, and prints each item it removes until lst is MAX_LENGTH items long. If lst is already shorter than MAX_LENGTH you should leave it unchanged. We've written a main() function for you which gets a list and passes it into your function once you run the program. For the autograder to pass you will need MAX_LENGTH to be 3, but feel free to change it around to test your program.
"""

print("08_shorten")

max_length:int = 3
def shorten(lst):
  while len(lst) >= max_length:
   last_element = lst.pop()
   print(last_element)

def get_list():
  lst = []
  elem:int = input("Enter an element add to the list: ")
  while elem != "":
    lst.append(elem)
    elem = input("Enter an element add to the list: ")
  return lst

def main():
    lst = get_list()
    shorten(lst)

if __name__ == "__main__":
    main()